### ISSUE TITLE
add

### ISSUE THREAD

**Issue by mhmh55516** [yunemse48/403bypasser#1]
Hi, please add this
![image](https://user-images.githubusercontent.com/28407784/95984687-dc717780-0e23-11eb-8e4a-5382150e43d3.png)

**Comment by yunemse48** [comment]
Great! I'll add this today and I'll inform you. Thanks.

**Comment by yunemse48** [comment]
I have added this to the tool but since I'm still working on some issues, I haven't committed it yet. I'll inform when the tool is updated. Thanks for your feedback and patience.

**Comment by yunemse48** [comment]
Hi @mhmh55516 ,

I've added the feature you requested. Could you please check it?

Thanks.
