### ISSUE TITLE
How do you do anything with it?

### ISSUE THREAD

**Issue by GabrielCrocker7** [yunemse48/403bypasser#6]
Along with the directions making absolutely no sense, I just don't even understand how to run it. I used the git thingy but I couldn't actually find the file anywhere. And when I just downloaded it normally it crashed on startup.

**Comment by yunemse48** [comment]
Usage instructions are clear. After cloning or downloading the repository, install the required modules via Pip. Then the tool is ready to be used. You need to provide two arguments: target URL and target directory. You can provide either a single input for both or a list, whatever you want. However, make sure that the latest version of Python is installed on your system. If you stuck again, please feel free to reach out to me again. 

Thanks.

**Comment by 5l1v3r1** [comment]
obviously it is another dirbuster varianr. nothing special

**Comment by yunemse48** [comment]
> obviously it is another dirbuster varianr. nothing special

**Comment by yunemse48** [comment]
> obviously it is another dirbuster varianr. nothing special

Absolutely it's not. If you have used dirbuster, you should have known that these tools have different purposes. One is used to discover content, whereas the other one is used to bypass restrictions on certain pages which return 403 status code. Therefore, these tools are completely and clearly different and for different purposes. 
Thanks.
