### ISSUE TITLE
If the URI does not have a directory, it is only a / directory, an error will be reported

### ISSUE THREAD

**Issue by Oldman19** [yunemse48/403bypasser#8]
If the URI does not have a directory, it is only a / directory, an error will be reported

**Comment by yunemse48** [comment]
Great catch mate! Thanks for your feedback. I'll look into this and get back to you soon. 

Have a great day,
@yunemse48

**Comment by yunemse48** [comment]
Hi @Oldman19 ,

The issue is now resolved. Could you please test it? You must now be able to scan root directory by `-d /` or `-d ` arguments.

Thanks.

**Comment by badcrack3r** [comment]
Hello @yunemse48 ,

I retested it and its working fine now

thanks for this tool!

**Comment by yunemse48** [comment]
Hi @badcrack3r,

Thanks for your interest and effort! Glad to hear that the tool works properly. 

Best wishes,
@yunemse48
